#!/usr/bin/env python3
"""
Telegram Bot for WinGo Predictions
Provides predictions via Telegram commands
"""

import asyncio
import logging
import httpx
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

# Configuration
BOT_TOKEN = "8796895729:AAHC1UiRlAdn2Ha87_mG3RDLwaUZG5Qcr40"
API_URL = "http://localhost:8000/api/state"

# Logging setup
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)
logger = logging.getLogger(__name__)


def get_prediction():
    """Fetch prediction from local API"""
    try:
        with httpx.Client(timeout=10) as client:
            response = client.get(API_URL)
            if response.status_code == 200:
                return response.json()
            else:
                logger.error(f"API returned status {response.status_code}")
                return None
    except Exception as e:
        logger.error(f"Error fetching prediction: {e}")
        return None


def format_prediction_message(data):
    """Format prediction data for Telegram message"""
    if not data:
        return "❌ Error: Unable to fetch prediction"
    
    try:
        prediction = data.get('prediction', 'N/A')
        confidence = data.get('confidence', 0)
        target_num = data.get('targetNum', 'N/A')
        hedge_num = data.get('hedgeNum', 'N/A')
        current_issue = data.get('currentIssue', 'N/A')
        next_issue = data.get('nextIssue', 'N/A')
        pattern = data.get('patternName', 'N/A')
        source = data.get('source', 'N/A')
        
        message = f"""
🎯 <b>WinGo Prediction</b>

📊 <b>Prediction</b>: {prediction}
🎲 <b>Target Number</b>: {target_num}
🛡️ <b>Hedge Number</b>: {hedge_num}
📈 <b>Confidence</b>: {confidence}%

🔢 <b>Current Issue</b>: {current_issue}
➡️ <b>Next Issue</b>: {next_issue}

🧬 <b>Pattern</b>: {pattern}
🤖 <b>Source</b>: {source}

⏰ <b>Generated by EVOSEQ AI Engine</b>
        """
        return message.strip()
    except Exception as e:
        logger.error(f"Error formatting message: {e}")
        return "❌ Error: Unable to format prediction"


async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /start command"""
    welcome_message = """
🎰 <b>WinGo Prediction Bot</b>

Welcome! I provide AI-powered predictions for WinGo lottery.

<b>Commands:</b>
/predict - Get current prediction
/status - Check bot status
/help - Show this help message

⚠️ <b>Disclaimer</b>: Predictions are for entertainment purposes only. Not financial advice.
    """
    await update.message.reply_text(welcome_message.strip(), parse_mode='HTML')


async def predict_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /predict command"""
    await update.message.reply_text("🔄 Fetching prediction...")
    
    # Get prediction from API
    prediction_data = get_prediction()
    
    # Format and send
    message = format_prediction_message(prediction_data)
    await update.message.reply_text(message, parse_mode='HTML')


async def status_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /status command"""
    try:
        prediction_data = get_prediction()
        if prediction_data:
            status = "✅ Online and functioning"
            last_issue = prediction_data.get('currentIssue', 'N/A')
            confidence = prediction_data.get('confidence', 0)
            message = f"""
📊 <b>Bot Status</b>

{status}

🔢 <b>Last Issue</b>: {last_issue}
📈 <b>Last Confidence</b>: {confidence}%

🤖 <b>EVOSEQ Engine</b>: Running
📍 <b>Server</b>: AWS EC2
            """
        else:
            status = "❌ API Error"
            message = f"""
📊 <b>Bot Status</b>

{status}

⚠️ Unable to connect to prediction API
            """
    except Exception as e:
        message = f"❌ Error: {str(e)}"
    
    await update.message.reply_text(message.strip(), parse_mode='HTML')


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /help command"""
    help_message = """
🎰 <b>WinGo Prediction Bot Help</b>

<b>Available Commands:</b>
/start - Start the bot and see welcome message
/predict - Get current AI prediction
/status - Check bot and API status
/help - Show this help message

<b>Features:</b>
• Real-time AI predictions
• Confidence scores
• Pattern analysis
• Multiple model ensemble

<b>About:</b>
Powered by EVOSEQ - Evolving Intelligence Engine
Uses Transformer, Mamba, and S4D models
Statistical analysis and pattern recognition

⚠️ <b>Disclaimer</b>: For entertainment purposes only.
    """
    await update.message.reply_text(help_message.strip(), parse_mode='HTML')


async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle errors"""
    logger.error(f"Update {update} caused error {context.error}")
    if update and update.message:
        await update.message.reply_text("❌ An error occurred. Please try again.")


def main():
    """Start the bot"""
    # Create application
    application = Application.builder().token(BOT_TOKEN).build()
    
    # Add command handlers
    application.add_handler(CommandHandler("start", start_command))
    application.add_handler(CommandHandler("predict", predict_command))
    application.add_handler(CommandHandler("status", status_command))
    application.add_handler(CommandHandler("help", help_command))
    
    # Add error handler
    application.add_error_handler(error_handler)
    
    # Start the bot
    logger.info("Starting WinGo Prediction Bot...")
    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()