#!/usr/bin/env python3
"""
Telegram Bot for WinGo Predictions
Provides predictions via Telegram commands and automatic updates
"""

import asyncio
import logging
import httpx
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

# Configuration
BOT_TOKEN = "8796895729:AAHC1UiRlAdn2Ha87_mG3RDLwaUZG5Qcr40"
API_URL = "http://localhost:8000/api/state"
CHECK_INTERVAL = 30  # Check for new predictions every 30 seconds

# Store for subscribed users and last prediction
subscribed_users = set()
last_prediction_issue = None
last_prediction = None  # Store last prediction data for win/loss tracking

# Logging setup
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)
logger = logging.getLogger(__name__)


def get_prediction():
    """Fetch prediction from local API"""
    try:
        with httpx.Client(timeout=10) as client:
            response = client.get(API_URL)
            if response.status_code == 200:
                return response.json()
            else:
                logger.error(f"API returned status {response.status_code}")
                return None
    except Exception as e:
        logger.error(f"Error fetching prediction: {e}")
        return None


def check_win_loss(previous_prediction, current_data):
    """Check if previous prediction was correct"""
    if not previous_prediction or not current_data:
        return None
    
    try:
        # For win/loss tracking, we need access to actual results
        # This requires the API to provide historical outcomes
        # Since the current API doesn't provide this, we'll skip for now
        # TODO: Implement when API results endpoint is available
        return None
            
    except Exception as e:
        logger.error(f"Error checking win/loss: {e}")
        return None


def format_prediction_message(data, previous_result=None):
    """Format prediction data for Telegram message"""
    if not data:
        return "❌ Error: Unable to fetch prediction"
    
    try:
        prediction = data.get('prediction', 'N/A')
        confidence = data.get('confidence', 0)
        target_num = data.get('targetNum', 'N/A')
        hedge_num = data.get('hedgeNum', 'N/A')
        current_issue = data.get('currentIssue', 'N/A')
        next_issue = data.get('nextIssue', 'N/A')
        pattern = data.get('patternName', 'N/A')
        source = data.get('source', 'N/A')
        
        # Add win/loss tracking if available
        result_info = ""
        if previous_result:
            result_emoji = "✅" if previous_result['won'] else "❌"
            result_text = "WON" if previous_result['won'] else "LOST"
            result_info = f"\n{result_emoji} <b>Previous Result</b>: {result_text} (Issue: {previous_result['issue']})"
        
        message = f"""
🎯 <b>WinGo Prediction</b>

📊 <b>Prediction</b>: {prediction}
🎲 <b>Target Number</b>: {target_num}
🛡️ <b>Hedge Number</b>: {hedge_num}
📈 <b>Confidence</b>: {confidence}%

🔢 <b>Current Issue</b>: {current_issue}
➡️ <b>Next Issue</b>: {next_issue}
{result_info}
🧬 <b>Pattern</b>: {pattern}
🤖 <b>Source</b>: {source}

⏰ <b>Generated by EVOSEQ AI Engine</b>
        """
        return message.strip()
    except Exception as e:
        logger.error(f"Error formatting message: {e}")
        return "❌ Error: Unable to format prediction"


async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /start command"""
    user_id = update.effective_chat.id
    subscribed_users.add(user_id)
    
    welcome_message = """
🎰 <b>WinGo Prediction Bot</b>

Welcome! I provide AI-powered predictions for WinGo lottery.

✅ <b>You are now subscribed to automatic prediction updates!</b>

<b>Commands:</b>
/predict - Get current prediction
/status - Check bot status
/subscribe - Subscribe to automatic updates
/unsubscribe - Unsubscribe from automatic updates
/help - Show this help message

⚠️ <b>Disclaimer</b>: Predictions are for entertainment purposes only. Not financial advice.
    """
    await update.message.reply_text(welcome_message.strip(), parse_mode='HTML')


async def predict_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /predict command"""
    await update.message.reply_text("🔄 Fetching prediction...")
    
    # Get prediction from API
    prediction_data = get_prediction()
    
    # Format and send
    message = format_prediction_message(prediction_data)
    await update.message.reply_text(message, parse_mode='HTML')


async def status_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /status command"""
    try:
        prediction_data = get_prediction()
        if prediction_data:
            status = "✅ Online and functioning"
            last_issue = prediction_data.get('currentIssue', 'N/A')
            confidence = prediction_data.get('confidence', 0)
            message = f"""
📊 <b>Bot Status</b>

{status}

🔢 <b>Last Issue</b>: {last_issue}
📈 <b>Last Confidence</b>: {confidence}%

🤖 <b>EVOSEQ Engine</b>: Running
📍 <b>Server</b>: AWS EC2
            """
        else:
            status = "❌ API Error"
            message = f"""
📊 <b>Bot Status</b>

{status}

⚠️ Unable to connect to prediction API
            """
    except Exception as e:
        message = f"❌ Error: {str(e)}"
    
    await update.message.reply_text(message.strip(), parse_mode='HTML')


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /help command"""
    help_message = """
🎰 <b>WinGo Prediction Bot Help</b>

<b>Available Commands:</b>
/start - Start the bot and see welcome message
/predict - Get current AI prediction
/status - Check bot and API status
/subscribe - Subscribe to automatic prediction updates
/unsubscribe - Unsubscribe from automatic updates
/help - Show this help message

<b>Features:</b>
• Real-time AI predictions
• Automatic updates when new predictions available
• Confidence scores
• Pattern analysis
• Multiple model ensemble

<b>About:</b>
Powered by EVOSEQ - Evolving Intelligence Engine
Uses Transformer, Mamba, and S4D models
Statistical analysis and pattern recognition

⚠️ <b>Disclaimer</b>: For entertainment purposes only.
    """
    await update.message.reply_text(help_message.strip(), parse_mode='HTML')


async def subscribe_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /subscribe command"""
    user_id = update.effective_chat.id
    subscribed_users.add(user_id)
    await update.message.reply_text("✅ You are now subscribed to automatic prediction updates!")


async def unsubscribe_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /unsubscribe command"""
    user_id = update.effective_chat.id
    if user_id in subscribed_users:
        subscribed_users.remove(user_id)
        await update.message.reply_text("❌ You have been unsubscribed from automatic updates.")
    else:
        await update.message.reply_text("You are not subscribed to automatic updates.")


async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle errors"""
    logger.error(f"Update {update} caused error {context.error}")
    if update and update.message:
        await update.message.reply_text("❌ An error occurred. Please try again.")


async def check_and_send_predictions(context: ContextTypes.DEFAULT_TYPE):
    """Check for new predictions and send to subscribed users"""
    global last_prediction_issue, last_prediction
    
    try:
        prediction_data = get_prediction()
        if not prediction_data:
            return
        
        current_issue = prediction_data.get('currentIssue')
        next_issue = prediction_data.get('nextIssue')
        
        # Check if this is a new prediction (based on next issue)
        # We want to send prediction for the upcoming issue, not current
        if next_issue and next_issue != last_prediction_issue:
            logger.info(f"New prediction detected for issue: {next_issue}")
            last_prediction_issue = next_issue
            
            # Check win/loss for previous prediction
            previous_result = None
            if last_prediction:
                previous_result = check_win_loss(last_prediction, prediction_data)
            
            # Send to all subscribed users
            message = format_prediction_message(prediction_data, previous_result)
            
            for user_id in subscribed_users.copy():  # Use copy to avoid modification during iteration
                try:
                    await context.bot.send_message(
                        chat_id=user_id,
                        text=message,
                        parse_mode='HTML'
                    )
                    logger.info(f"Sent prediction to user {user_id}")
                except Exception as e:
                    logger.error(f"Failed to send to user {user_id}: {e}")
                    # Remove user if they blocked the bot or chat doesn't exist
                    subscribed_users.discard(user_id)
            
            # Store this prediction for next win/loss check
            last_prediction = prediction_data
                    
    except Exception as e:
        logger.error(f"Error in prediction check: {e}")


async def prediction_updater(bot):
    """Background task to check for new predictions periodically"""
    while True:
        try:
            # Create a mock context with the bot
            class MockContext:
                def __init__(self, bot):
                    self.bot = bot
            
            context = MockContext(bot)
            await check_and_send_predictions(context)
        except Exception as e:
            logger.error(f"Error in prediction updater: {e}")
        
        await asyncio.sleep(CHECK_INTERVAL)


async def main():
    """Start the bot"""
    # Create application
    application = Application.builder().token(BOT_TOKEN).build()
    
    # Add command handlers
    application.add_handler(CommandHandler("start", start_command))
    application.add_handler(CommandHandler("predict", predict_command))
    application.add_handler(CommandHandler("status", status_command))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("subscribe", subscribe_command))
    application.add_handler(CommandHandler("unsubscribe", unsubscribe_command))
    
    # Add error handler
    application.add_error_handler(error_handler)
    
    # Start the bot
    logger.info("Starting WinGo Prediction Bot...")
    
    # Start background prediction updater
    asyncio.create_task(prediction_updater(application.bot))
    
    # Run the bot
    await application.initialize()
    await application.start()
    await application.updater.start_polling()
    
    # Keep the bot running
    try:
        await asyncio.Event().wait()
    except KeyboardInterrupt:
        logger.info("Bot stopped by user")
    finally:
        await application.updater.stop()
        await application.stop()
        await application.shutdown()


if __name__ == "__main__":
    asyncio.run(main())


if __name__ == "__main__":
    main()