from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import os
import sys
import json
from datetime import datetime

# Load environment variables from .env file FIRST
try:
    from dotenv import load_dotenv
    backend_dir = os.path.dirname(os.path.abspath(__file__))
    env_file = os.path.join(backend_dir, '.env')
    if os.path.exists(env_file):
        load_dotenv(env_file)
        print("[SERVER] Loaded .env from", env_file)
except Exception as e:
    print(f"[SERVER] Warning: Could not load .env: {e}")

# Force unbuffered output for Render logging
sys.stdout.reconfigure(line_buffering=True)

# Ensure local imports work in all environments
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.database import SessionLocal, AIBrainState, PredictionAudit, save_live_draws

# ---------------------------------------------------------------------------
# EVOSEQ Adaptive Intelligence Engine v3 — lazy import bridge
# Import is guarded because the server runs on Render free tier which may not
# have a full ML runtime installed. Falls back gracefully on error.
# ---------------------------------------------------------------------------
_BRIDGE = None
_BRIDGE_IMPORT_ERROR = None


def _get_bridge():
    """Lazily instantiate the EVOSEQBridge singleton."""
    global _BRIDGE, _BRIDGE_IMPORT_ERROR
    if _BRIDGE is not None:
        return _BRIDGE
    if _BRIDGE_IMPORT_ERROR is not None:
        return None
    try:
        from backend.evoseq_bridge import get_bridge as _gb
        _BRIDGE = _gb()
        return _BRIDGE
    except Exception as _e:
        _BRIDGE_IMPORT_ERROR = str(_e)
        print(f"[SERVER] Bridge unavailable: {_e}", flush=True)
        return None


app = FastAPI(title="WinGo Database Gateway - Free Tier Optimized")

# Allow all origins for Vercel + Localhost
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
@app.get("/healthz")
def health_check():
    return {
        "status": "online",
        "service": "WinGo Database Gateway",
        "role": "Database Storage Only (Free Tier)",
        "note": "Lightweight API for database operations. ML runs locally."
    }

@app.get("/api/health")
def api_health():
    return {"status": "ok", "timestamp": datetime.now().isoformat()}

@app.get("/api/state")
def get_api_state():
    """
    Return the latest prediction from the LOCAL ENGINE stored in database.
    This is a lightweight read operation optimized for free tier.
    """
    db = SessionLocal()
    try:
        # Read the prediction generated by the local engine
        live_state = db.query(AIBrainState).filter(
            AIBrainState.model_name == "Live_UI_State"
        ).order_by(AIBrainState.id.desc()).first()
        
        if live_state and live_state.synaptic_weights:
            try:
                prediction = json.loads(live_state.synaptic_weights)
                prediction["source"] = "local_engine"
                return prediction
            except Exception as e:
                print(f"Error parsing prediction: {e}")
                return {"error": "Invalid prediction data", "status": "no_prediction"}
        else:
            return {"error": "No prediction available yet", "status": "waiting_for_local_engine"}
    finally:
        db.close()

@app.get("/api/metrics")
def prediction_metrics():
    """Return outcome-based metrics from forecasts that have been reconciled."""
    db = SessionLocal()
    try:
        rows = db.query(PredictionAudit).filter(PredictionAudit.actual_size.isnot(None)).all()
        if not rows:
            return {"resolved_predictions": 0, "status": "collecting_evidence"}
        accuracy = sum(1 for row in rows if row.is_correct) / len(rows)
        brier_rows = [row.brier_score for row in rows if row.brier_score is not None]
        log_loss_rows = [row.log_loss for row in rows if row.log_loss is not None]
        return {
            "resolved_predictions": len(rows),
            "directional_accuracy": round(accuracy, 4),
            "brier_score": round(sum(brier_rows) / len(brier_rows), 4) if brier_rows else None,
            "log_loss": round(sum(log_loss_rows) / len(log_loss_rows), 4) if log_loss_rows else None,
        }
    finally:
        db.close()

@app.post("/api/state")
def post_api_state(payload: dict | None = None):
    """Accept but ignore client payloads - local engine is the source of truth."""
    return get_api_state()

@app.post("/api/outcomes")
def save_outcomes(outcomes: list):
    """
    Lightweight endpoint to save outcomes to database.
    Called by local scraper to store data in cloud database.
    """
    db = SessionLocal()
    try:
        new_draws = save_live_draws(db, outcomes)
        return {
            "status": "success",
            "new_draws_saved": new_draws,
            "total_outcomes": len(outcomes)
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        db.close()

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8080))
    print(f"🚀 Starting Lightweight Database Gateway on 0.0.0.0:{port}", flush=True)
    print("💾 Free Tier Optimized: Database storage only", flush=True)
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
