from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import asyncio
import os
import sys
import json
from datetime import datetime

# Load environment variables from .env file FIRST
try:
    from dotenv import load_dotenv
    backend_dir = os.path.dirname(os.path.abspath(__file__))
    env_file = os.path.join(backend_dir, '.env')
    if os.path.exists(env_file):
        load_dotenv(env_file)
        print("[SERVER] Loaded .env from", env_file)
except Exception as e:
    print(f"[SERVER] Warning: Could not load .env: {e}")

# Force unbuffered output for Render logging
sys.stdout.reconfigure(line_buffering=True)

# Ensure local imports work in all environments
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.scraper import run_scraper_daemon
from backend.database import SessionLocal, AIBrainState

app = FastAPI(title="WinGo Prediction API - Render Backend")

# Allow all origins for Vercel + Localhost
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
async def startup_event():
    # Spawn lightweight cloud scraper daemon only
    # ALL prediction logic runs locally on your Mac
    print("☁️ Spawning Render Cloud Scraper (Historical Data Collection)...")
    asyncio.create_task(run_scraper_daemon(max_duration_seconds=999999999))

@app.get("/")
@app.get("/healthz")
def health_check():
    return {
        "status": "online",
        "service": "WinGo Render Backend",
        "role": "Cloud Scraper + API Gateway",
        "note": "Predictions from local_ai_engine.py running on your Mac"
    }

@app.get("/api/health")
def api_health():
    return {"status": "ok", "timestamp": datetime.now().isoformat()}

@app.get("/api/state")
def get_api_state():
    """
    Return the latest prediction from the LOCAL ENGINE stored in Supabase.
    Render acts ONLY as a gateway to read this data.
    """
    db = SessionLocal()
    try:
        # Read the prediction generated by the local engine
        live_state = db.query(AIBrainState).filter(
            AIBrainState.model_name == "Live_UI_State"
        ).order_by(AIBrainState.id.desc()).first()
        
        if live_state and live_state.synaptic_weights:
            try:
                prediction = json.loads(live_state.synaptic_weights)
                prediction["source"] = "local_engine"
                return prediction
            except Exception as e:
                print(f"Error parsing prediction: {e}")
                return {"error": "Invalid prediction data", "status": "no_prediction"}
        else:
            return {"error": "No prediction available yet", "status": "waiting_for_local_engine"}
    finally:
        db.close()

@app.post("/api/state")
def post_api_state(payload: dict | None = None):
    """Accept but ignore client payloads - local engine is the source of truth."""
    return get_api_state()

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8080))
    print(f"🚀 Starting Render Backend on 0.0.0.0:{port}", flush=True)
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
